//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SalesPlanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalesPlanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLayer.SalesPlanResources", typeof(SalesPlanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0}(s) Selected.
        /// </summary>
        public static string AllValuesSelected {
            get {
                return ResourceManager.GetString("AllValuesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string applicationtypeExcel {
            get {
                return ResourceManager.GetString("applicationtypeExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string applicationTypePDF {
            get {
                return ResourceManager.GetString("applicationTypePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        public static string arraySep {
            get {
                return ResourceManager.GetString("arraySep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #x21E9.
        /// </summary>
        public static string arrowDown {
            get {
                return ResourceManager.GetString("arrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #x21E7.
        /// </summary>
        public static string arrowUp {
            get {
                return ResourceManager.GetString("arrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy HH:mm.
        /// </summary>
        public static string asofMask {
            get {
                return ResourceManager.GetString("asofMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment;filename=.
        /// </summary>
        public static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Code).
        /// </summary>
        public static string blankVal {
            get {
                return ResourceManager.GetString("blankVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanks.
        /// </summary>
        public static string BlankWord {
            get {
                return ResourceManager.GetString("BlankWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Data.
        /// </summary>
        public static string btnFillDataLabel {
            get {
                return ResourceManager.GetString("btnFillDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refilter Data.
        /// </summary>
        public static string btnRefreshDataLabel {
            get {
                return ResourceManager.GetString("btnRefreshDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string btnTextSelectAll {
            get {
                return ResourceManager.GetString("btnTextSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string btnTextUnselectAll {
            get {
                return ResourceManager.GetString("btnTextUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string colCode {
            get {
                return ResourceManager.GetString("colCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string colColor {
            get {
                return ResourceManager.GetString("colColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string colColorWidth {
            get {
                return ResourceManager.GetString("colColorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER.
        /// </summary>
        public static string colCUSTOMER {
            get {
                return ResourceManager.GetString("colCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string colCustWidth {
            get {
                return ResourceManager.GetString("colCustWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string colDesc {
            get {
                return ResourceManager.GetString("colDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string colDESCRIPTION {
            get {
                return ResourceManager.GetString("colDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAIL.
        /// </summary>
        public static string colDETAIL {
            get {
                return ResourceManager.GetString("colDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dryness.
        /// </summary>
        public static string colDryness {
            get {
                return ResourceManager.GetString("colDryness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp/Prg ID.
        /// </summary>
        public static string ColExpPrgId {
            get {
                return ResourceManager.GetString("ColExpPrgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grade.
        /// </summary>
        public static string colgrade {
            get {
                return ResourceManager.GetString("colgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string colGradeWith {
            get {
                return ResourceManager.GetString("colGradeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |INV|.
        /// </summary>
        public static string colINV {
            get {
                return ResourceManager.GetString("colINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string colLength {
            get {
                return ResourceManager.GetString("colLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC.
        /// </summary>
        public static string colLOC {
            get {
                return ResourceManager.GetString("colLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCDESC.
        /// </summary>
        public static string colLOCDESC {
            get {
                return ResourceManager.GetString("colLOCDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCTYPE.
        /// </summary>
        public static string colLOCTYPE {
            get {
                return ResourceManager.GetString("colLOCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string colMathWidth {
            get {
                return ResourceManager.GetString("colMathWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGD.
        /// </summary>
        public static string colMGD {
            get {
                return ResourceManager.GetString("colMGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mgr.
        /// </summary>
        public static string colMGR {
            get {
                return ResourceManager.GetString("colMGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180.
        /// </summary>
        public static string colMGRWidth {
            get {
                return ResourceManager.GetString("colMGRWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPrint.
        /// </summary>
        public static string colNoPrint {
            get {
                return ResourceManager.GetString("colNoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string colNoPrintWidth {
            get {
                return ResourceManager.GetString("colNoPrintWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string colon {
            get {
                return ResourceManager.GetString("colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDNUM.
        /// </summary>
        public static string colORDNUM {
            get {
                return ResourceManager.GetString("colORDNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string colOwner {
            get {
                return ResourceManager.GetString("colOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P13.
        /// </summary>
        public static string colP13 {
            get {
                return ResourceManager.GetString("colP13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4.
        /// </summary>
        public static string colP4 {
            get {
                return ResourceManager.GetString("colP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P8.
        /// </summary>
        public static string colP8 {
            get {
                return ResourceManager.GetString("colP8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAST.
        /// </summary>
        public static string colPAST {
            get {
                return ResourceManager.GetString("colPAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        public static string colPRODUCT {
            get {
                return ResourceManager.GetString("colPRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string colPRODUCTWidth {
            get {
                return ResourceManager.GetString("colPRODUCTWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTYPE.
        /// </summary>
        public static string colPROTYPE {
            get {
                return ResourceManager.GetString("colPROTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string colRegion {
            get {
                return ResourceManager.GetString("colRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowType.
        /// </summary>
        public static string colRowType {
            get {
                return ResourceManager.GetString("colRowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string colSort {
            get {
                return ResourceManager.GetString("colSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string colSortWidth {
            get {
                return ResourceManager.GetString("colSortWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specie.
        /// </summary>
        public static string colspecie {
            get {
                return ResourceManager.GetString("colspecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        public static string colSpecieWidth {
            get {
                return ResourceManager.GetString("colSpecieWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string colSurface {
            get {
                return ResourceManager.GetString("colSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thick.
        /// </summary>
        public static string colthick {
            get {
                return ResourceManager.GetString("colthick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string colThickWidth {
            get {
                return ResourceManager.GetString("colThickWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string colTotal {
            get {
                return ResourceManager.GetString("colTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string colTotalWidth {
            get {
                return ResourceManager.GetString("colTotalWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string colTYPE {
            get {
                return ResourceManager.GetString("colTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string colTypeWidth {
            get {
                return ResourceManager.GetString("colTypeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string colUOM {
            get {
                return ResourceManager.GetString("colUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W00.
        /// </summary>
        public static string colW00 {
            get {
                return ResourceManager.GetString("colW00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W01.
        /// </summary>
        public static string colW01 {
            get {
                return ResourceManager.GetString("colW01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W02.
        /// </summary>
        public static string colW02 {
            get {
                return ResourceManager.GetString("colW02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W03.
        /// </summary>
        public static string colW03 {
            get {
                return ResourceManager.GetString("colW03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W04.
        /// </summary>
        public static string colW04 {
            get {
                return ResourceManager.GetString("colW04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W05.
        /// </summary>
        public static string colW05 {
            get {
                return ResourceManager.GetString("colW05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W06.
        /// </summary>
        public static string colW06 {
            get {
                return ResourceManager.GetString("colW06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W07.
        /// </summary>
        public static string colW07 {
            get {
                return ResourceManager.GetString("colW07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W08.
        /// </summary>
        public static string colW08 {
            get {
                return ResourceManager.GetString("colW08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W09.
        /// </summary>
        public static string colW09 {
            get {
                return ResourceManager.GetString("colW09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W10.
        /// </summary>
        public static string colW10 {
            get {
                return ResourceManager.GetString("colW10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W11.
        /// </summary>
        public static string colW11 {
            get {
                return ResourceManager.GetString("colW11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W12.
        /// </summary>
        public static string colW12 {
            get {
                return ResourceManager.GetString("colW12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W13.
        /// </summary>
        public static string colW13 {
            get {
                return ResourceManager.GetString("colW13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string colWidth {
            get {
                return ResourceManager.GetString("colWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content-Disposition.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.fff.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_dd_yyyy.
        /// </summary>
        public static string dateMask {
            get {
                return ResourceManager.GetString("dateMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        public static string datePara {
            get {
                return ResourceManager.GetString("datePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string datePrintMask {
            get {
                return ResourceManager.GetString("datePrintMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string dblQuotes {
            get {
                return ResourceManager.GetString("dblQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        public static string eol {
            get {
                return ResourceManager.GetString("eol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  = .
        /// </summary>
        public static string equal {
            get {
                return ResourceManager.GetString("equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That Column is already at the bottom.
        /// </summary>
        public static string errCantMoveDown {
            get {
                return ResourceManager.GetString("errCantMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That Column is already at the top.
        /// </summary>
        public static string errCantMoveUp {
            get {
                return ResourceManager.GetString("errCantMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sort/grouping columns to move.
        /// </summary>
        public static string errNothingToMove {
            get {
                return ResourceManager.GetString("errNothingToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error Error occurred while attempting to execute procedure {0}, error is {1} - {2}.
        /// </summary>
        public static string errOnDataBase {
            get {
                return ResourceManager.GetString("errOnDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a column name from the list of available columns and then click the button again.
        /// </summary>
        public static string errSelectColAvail {
            get {
                return ResourceManager.GetString("errSelectColAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a color to continue.
        /// </summary>
        public static string errSelectColor {
            get {
                return ResourceManager.GetString("errSelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a column from the the list of Sort/Grouping Columns and then click the button again.
        /// </summary>
        public static string errSelectColSort {
            get {
                return ResourceManager.GetString("errSelectColSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a column from the list of Sort/Grouping Columns to reorder and then click the button again.
        /// </summary>
        public static string errSelectColToReorder {
            get {
                return ResourceManager.GetString("errSelectColToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer to continue.
        /// </summary>
        public static string errSelectCust {
            get {
                return ResourceManager.GetString("errSelectCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a grade to continue.
        /// </summary>
        public static string errSelectGrade {
            get {
                return ResourceManager.GetString("errSelectGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Mgr to continue.
        /// </summary>
        public static string errSelectMgr {
            get {
                return ResourceManager.GetString("errSelectMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a region to continue.
        /// </summary>
        public static string errSelectRegion {
            get {
                return ResourceManager.GetString("errSelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sort to continue.
        /// </summary>
        public static string errSelectSort {
            get {
                return ResourceManager.GetString("errSelectSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a species to continue.
        /// </summary>
        public static string errSelectSpecies {
            get {
                return ResourceManager.GetString("errSelectSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a thickness to continue.
        /// </summary>
        public static string errSelectThick {
            get {
                return ResourceManager.GetString("errSelectThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type to continue.
        /// </summary>
        public static string errSelectType {
            get {
                return ResourceManager.GetString("errSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while exporting to Excel.
        /// </summary>
        public static string excelError {
            get {
                return ResourceManager.GetString("excelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        public static string excelExtension {
            get {
                return ResourceManager.GetString("excelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales_Plan_.
        /// </summary>
        public static string exportFileName {
            get {
                return ResourceManager.GetString("exportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND .
        /// </summary>
        public static string filterANDConnector {
            get {
                return ResourceManager.GetString("filterANDConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) .
        /// </summary>
        public static string filterCloseParen {
            get {
                return ResourceManager.GetString("filterCloseParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (.
        /// </summary>
        public static string filterOpenParen {
            get {
                return ResourceManager.GetString("filterOpenParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OR .
        /// </summary>
        public static string filterORConnector {
            get {
                return ResourceManager.GetString("filterORConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} = &apos;{1}&apos;.
        /// </summary>
        public static string filterString {
            get {
                return ResourceManager.GetString("filterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helvetica.
        /// </summary>
        public static string fontHelvetica {
            get {
                return ResourceManager.GetString("fontHelvetica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} = {1}.
        /// </summary>
        public static string hdrFilterString {
            get {
                return ResourceManager.GetString("hdrFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string letterW {
            get {
                return ResourceManager.GetString("letterW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListOrderedColumnWidths.
        /// </summary>
        public static string lstColWidths {
            get {
                return ResourceManager.GetString("lstColWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridColumnDirectory.
        /// </summary>
        public static string lstGridCols {
            get {
                return ResourceManager.GetString("lstGridCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridColumnWidths.
        /// </summary>
        public static string lstGridWide {
            get {
                return ResourceManager.GetString("lstGridWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListGroupColumns.
        /// </summary>
        public static string lstGroupCols {
            get {
                return ResourceManager.GetString("lstGroupCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListHiddenColumns.
        /// </summary>
        public static string lstHideCols {
            get {
                return ResourceManager.GetString("lstHideCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedTotalColumns.
        /// </summary>
        public static string lstMathCols {
            get {
                return ResourceManager.GetString("lstMathCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableFoundProducts.
        /// </summary>
        public static string lstProducts {
            get {
                return ResourceManager.GetString("lstProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionsList.
        /// </summary>
        public static string lstRegions {
            get {
                return ResourceManager.GetString("lstRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListSelectedRegions.
        /// </summary>
        public static string lstSelRegions {
            get {
                return ResourceManager.GetString("lstSelRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string maxGridColumns {
            get {
                return ResourceManager.GetString("maxGridColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string noneSelected {
            get {
                return ResourceManager.GetString("noneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0}(s) Selected.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        public static string pagePara {
            get {
                return ResourceManager.GetString("pagePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while generating PDF.
        /// </summary>
        public static string pdfError {
            get {
                return ResourceManager.GetString("pdfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        public static string pdfFileExtension {
            get {
                return ResourceManager.GetString("pdfFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Availabiliity as of {0}.
        /// </summary>
        public static string pdfSubject {
            get {
                return ResourceManager.GetString("pdfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Plan.
        /// </summary>
        public static string pdfTitle {
            get {
                return ResourceManager.GetString("pdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string rowTotals {
            get {
                return ResourceManager.GetString("rowTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVEN.
        /// </summary>
        public static string rowTypeInven {
            get {
                return ResourceManager.GetString("rowTypeInven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES H.
        /// </summary>
        public static string rowTypeOrdHist {
            get {
                return ResourceManager.GetString("rowTypeOrdHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOLDS.
        /// </summary>
        public static string rowTypeOrdHolds {
            get {
                return ResourceManager.GetString("rowTypeOrdHolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROD.
        /// </summary>
        public static string rowTypeProd {
            get {
                return ResourceManager.GetString("rowTypeProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROD H.
        /// </summary>
        public static string rowTypeProdHist {
            get {
                return ResourceManager.GetString("rowTypeProdHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES.
        /// </summary>
        public static string rowTypeSales {
            get {
                return ResourceManager.GetString("rowTypeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesLevels.
        /// </summary>
        public static string SalesLevels {
            get {
                return ResourceManager.GetString("SalesLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesTotals.
        /// </summary>
        public static string SalesTotals {
            get {
                return ResourceManager.GetString("SalesTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedAvailableColumn.
        /// </summary>
        public static string selAvailCol {
            get {
                return ResourceManager.GetString("selAvailCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedBoth.
        /// </summary>
        public static string SelectBoth {
            get {
                return ResourceManager.GetString("SelectBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedGrade.
        /// </summary>
        public static string selGrade {
            get {
                return ResourceManager.GetString("selGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedLocations.
        /// </summary>
        public static string selLocations {
            get {
                return ResourceManager.GetString("selLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedProType.
        /// </summary>
        public static string selProType {
            get {
                return ResourceManager.GetString("selProType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedSortColumn.
        /// </summary>
        public static string selSortCol {
            get {
                return ResourceManager.GetString("selSortCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedSpecies.
        /// </summary>
        public static string selSpecies {
            get {
                return ResourceManager.GetString("selSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedThickness.
        /// </summary>
        public static string selThickness {
            get {
                return ResourceManager.GetString("selThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlName.
        /// </summary>
        public static string settingsColControlName {
            get {
                return ResourceManager.GetString("settingsColControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlValue.
        /// </summary>
        public static string settingsColControlValue {
            get {
                return ResourceManager.GetString("settingsColControlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string settingsColUserId {
            get {
                return ResourceManager.GetString("settingsColUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string sngQuotes {
            get {
                return ResourceManager.GetString("sngQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t delete the only sort/grouping column..
        /// </summary>
        public static string sortcolsError {
            get {
                return ResourceManager.GetString("sortcolsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ASC.
        /// </summary>
        public static string sortDir {
            get {
                return ResourceManager.GetString("sortDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations_Species_Color].
        /// </summary>
        public static string SpLoadColor {
            get {
                return ResourceManager.GetString("SpLoadColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_0_Inventory_NewDec].
        /// </summary>
        public static string SploadCurrInventory {
            get {
                return ResourceManager.GetString("SploadCurrInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations_Species_Grade].
        /// </summary>
        public static string SpLoadGrade {
            get {
                return ResourceManager.GetString("SpLoadGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_4_Hold_Orders_NewDec].
        /// </summary>
        public static string spLoadHoldOrds {
            get {
                return ResourceManager.GetString("spLoadHoldOrds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_Locations].
        /// </summary>
        public static string SpLoadLocations {
            get {
                return ResourceManager.GetString("SpLoadLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations_Species_NoPrint].
        /// </summary>
        public static string SpLoadNoPrint {
            get {
                return ResourceManager.GetString("SpLoadNoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_3_Open_Orders_NewDec].
        /// </summary>
        public static string SpLoadOpenOrds {
            get {
                return ResourceManager.GetString("SpLoadOpenOrds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_6_Order_History_NewDec].
        /// </summary>
        public static string SpLoadOrdHistory {
            get {
                return ResourceManager.GetString("SpLoadOrdHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IncludeBlankRegions.
        /// </summary>
        public static string spLoadParmIncludeBlank {
            get {
                return ResourceManager.GetString("spLoadParmIncludeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichLocation.
        /// </summary>
        public static string spLoadParmLocation {
            get {
                return ResourceManager.GetString("spLoadParmLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichProductType.
        /// </summary>
        public static string spLoadParmProType {
            get {
                return ResourceManager.GetString("spLoadParmProType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichRegion.
        /// </summary>
        public static string spLoadParmRegion {
            get {
                return ResourceManager.GetString("spLoadParmRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichSpecie.
        /// </summary>
        public static string spLoadParmSpecie {
            get {
                return ResourceManager.GetString("spLoadParmSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_2_Production_NewDec].
        /// </summary>
        public static string SpLoadProd {
            get {
                return ResourceManager.GetString("SpLoadProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_7_Production_History_NewDec].
        /// </summary>
        public static string SpLoadProdHIstory {
            get {
                return ResourceManager.GetString("SpLoadProdHIstory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_Product_Descriptions].
        /// </summary>
        public static string SpLoadProducts {
            get {
                return ResourceManager.GetString("SpLoadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType].
        /// </summary>
        public static string SpLoadProtypes {
            get {
                return ResourceManager.GetString("SpLoadProtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions].
        /// </summary>
        public static string SpLoadRegions {
            get {
                return ResourceManager.GetString("SpLoadRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations].
        /// </summary>
        public static string SpLoadRegionsLocations {
            get {
                return ResourceManager.GetString("SpLoadRegionsLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_retrieve_SalesPlan_Settings].
        /// </summary>
        public static string spLoadSettings {
            get {
                return ResourceManager.GetString("spLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations_Species_Sort].
        /// </summary>
        public static string SpLoadSort {
            get {
                return ResourceManager.GetString("SpLoadSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations_Species].
        /// </summary>
        public static string SpLoadSpecies {
            get {
                return ResourceManager.GetString("SpLoadSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_Retrieve_ProType_Regions_Locations_Species_Thickness].
        /// </summary>
        public static string SpLoadThickness {
            get {
                return ResourceManager.GetString("SpLoadThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBUS].[dbo].[usp_update_SalesPlan_Settings].
        /// </summary>
        public static string spSaveSettings {
            get {
                return ResourceManager.GetString("spSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ControlName.
        /// </summary>
        public static string spSettingsParmControlName {
            get {
                return ResourceManager.GetString("spSettingsParmControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ControlValue.
        /// </summary>
        public static string spSettingsParmControlValue {
            get {
                return ResourceManager.GetString("spSettingsParmControlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserId.
        /// </summary>
        public static string spSettingsParmUserId {
            get {
                return ResourceManager.GetString("spSettingsParmUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListCustomers.
        /// </summary>
        public static string strCust {
            get {
                return ResourceManager.GetString("strCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridDataTableSource.
        /// </summary>
        public static string strGrid {
            get {
                return ResourceManager.GetString("strGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listMgr.
        /// </summary>
        public static string strMgr {
            get {
                return ResourceManager.GetString("strMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lstmatchedProducts.
        /// </summary>
        public static string strProd {
            get {
                return ResourceManager.GetString("strProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListRowTypes.
        /// </summary>
        public static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lstColorTable.
        /// </summary>
        public static string tblColor {
            get {
                return ResourceManager.GetString("tblColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_Inven.
        /// </summary>
        public static string tblCurrInven {
            get {
                return ResourceManager.GetString("tblCurrInven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIlteredDataTable.
        /// </summary>
        public static string tblFiltered {
            get {
                return ResourceManager.GetString("tblFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string tblGrade {
            get {
                return ResourceManager.GetString("tblGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4_Ord_Hold.
        /// </summary>
        public static string tblHoldOrders {
            get {
                return ResourceManager.GetString("tblHoldOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc.
        /// </summary>
        public static string tblLocations {
            get {
                return ResourceManager.GetString("tblLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationRegionsXRef.
        /// </summary>
        public static string tblLocRegions {
            get {
                return ResourceManager.GetString("tblLocRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LstNoPrintTable.
        /// </summary>
        public static string tblNoPrint {
            get {
                return ResourceManager.GetString("tblNoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3_Ord_Open.
        /// </summary>
        public static string tblOpenOrders {
            get {
                return ResourceManager.GetString("tblOpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6_Ord_Hist.
        /// </summary>
        public static string tblOrderHist {
            get {
                return ResourceManager.GetString("tblOrderHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7_Prod_Hist.
        /// </summary>
        public static string tblProdHist {
            get {
                return ResourceManager.GetString("tblProdHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2_Prod.
        /// </summary>
        public static string tblProduction {
            get {
                return ResourceManager.GetString("tblProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductTypes.
        /// </summary>
        public static string tblProTypes {
            get {
                return ResourceManager.GetString("tblProTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainReportTable.
        /// </summary>
        public static string tblReport {
            get {
                return ResourceManager.GetString("tblReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LstSortTable.
        /// </summary>
        public static string tblSort {
            get {
                return ResourceManager.GetString("tblSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string tblSpecies {
            get {
                return ResourceManager.GetString("tblSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick.
        /// </summary>
        public static string tblThickness {
            get {
                return ResourceManager.GetString("tblThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Value).
        /// </summary>
        public static string textNoValue {
            get {
                return ResourceManager.GetString("textNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}.
        /// </summary>
        public static string timePara {
            get {
                return ResourceManager.GetString("timePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm tt.
        /// </summary>
        public static string timePrintMask {
            get {
                return ResourceManager.GetString("timePrintMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLastRetrieved.
        /// </summary>
        public static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column: {0}.
        /// </summary>
        public static string toolTipLocationColumn {
            get {
                return ResourceManager.GetString("toolTipLocationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row : .
        /// </summary>
        public static string toolTipLocationRow {
            get {
                return ResourceManager.GetString("toolTipLocationRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value : {0}.
        /// </summary>
        public static string toolTipValueRow {
            get {
                return ResourceManager.GetString("toolTipValueRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4_ORD_HOLDS.
        /// </summary>
        public static string typeHolds {
            get {
                return ResourceManager.GetString("typeHolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7_PROD_HIST.
        /// </summary>
        public static string typeProdHist {
            get {
                return ResourceManager.GetString("typeProdHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6_ORD_HIST.
        /// </summary>
        public static string typeSalesHIst {
            get {
                return ResourceManager.GetString("typeSalesHIst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string uScore {
            get {
                return ResourceManager.GetString("uScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string valueSep {
            get {
                return ResourceManager.GetString("valueSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  selection(s) are .
        /// </summary>
        public static string valuesSelectedAS {
            get {
                return ResourceManager.GetString("valuesSelectedAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILId.
        /// </summary>
        public static string vwColDetail {
            get {
                return ResourceManager.GetString("vwColDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDNUMId.
        /// </summary>
        public static string vwColORDNUM {
            get {
                return ResourceManager.GetString("vwColORDNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col{0}Id.
        /// </summary>
        public static string vwColumnName {
            get {
                return ResourceManager.GetString("vwColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string wordALL {
            get {
                return ResourceManager.GetString("wordALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTH.
        /// </summary>
        public static string wordBoth {
            get {
                return ResourceManager.GetString("wordBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dup.
        /// </summary>
        public static string wordDup {
            get {
                return ResourceManager.GetString("wordDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string wordID {
            get {
                return ResourceManager.GetString("wordID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGR:.
        /// </summary>
        public static string wordMgr {
            get {
                return ResourceManager.GetString("wordMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report .
        /// </summary>
        public static string wordReport {
            get {
                return ResourceManager.GetString("wordReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sub Total.
        /// </summary>
        public static string wordSubTotal {
            get {
                return ResourceManager.GetString("wordSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avail.
        /// </summary>
        public static string wordTotal {
            get {
                return ResourceManager.GetString("wordTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListItem.
        /// </summary>
        public static string xmlListItem {
            get {
                return ResourceManager.GetString("xmlListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string xmlselected {
            get {
                return ResourceManager.GetString("xmlselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string xmltext {
            get {
                return ResourceManager.GetString("xmltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string xmlvalue {
            get {
                return ResourceManager.GetString("xmlvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
