//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchProductsDataLayer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchProductsDataLayer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLayer.SearchProductsDataLayer", typeof(SearchProductsDataLayer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string CodeCol {
            get {
                return ResourceManager.GetString("CodeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionCol {
            get {
                return ResourceManager.GetString("DescriptionCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection criteria was supplied before clicking on the load button, please supply a selection criteria first.
        /// </summary>
        public static string ErrorNothingToSearchBy {
            get {
                return ResourceManager.GetString("ErrorNothingToSearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Searching by Product Type and Code both the Product Type and the Product Code mst be supplied.
        /// </summary>
        public static string ErrorSearchProdTypeCodeIncomplete {
            get {
                return ResourceManager.GetString("ErrorSearchProdTypeCodeIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichCodeList.
        /// </summary>
        public static string LoadPickListParm {
            get {
                return ResourceManager.GetString("LoadPickListParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @WhichProSet.
        /// </summary>
        public static string LoadPickListSet {
            get {
                return ResourceManager.GetString("LoadPickListSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBus].[dbo].[up_xferPickCodeList].
        /// </summary>
        public static string LoadPickListSproc {
            get {
                return ResourceManager.GetString("LoadPickListSproc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBus].[dbo].[up_xferProductCodeList].
        /// </summary>
        public static string LoadProductCode {
            get {
                return ResourceManager.GetString("LoadProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichProductCodeList.
        /// </summary>
        public static string LoadProductCodeParm {
            get {
                return ResourceManager.GetString("LoadProductCodeParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBus].[dbo].[up_xferProductTypeList].
        /// </summary>
        public static string LoadProductType {
            get {
                return ResourceManager.GetString("LoadProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewCode.
        /// </summary>
        public static string NewCodeCol {
            get {
                return ResourceManager.GetString("NewCodeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc10.
        /// </summary>
        public static string NewDesc10Col {
            get {
                return ResourceManager.GetString("NewDesc10Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc11.
        /// </summary>
        public static string NewDesc11Col {
            get {
                return ResourceManager.GetString("NewDesc11Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc12.
        /// </summary>
        public static string NewDesc12Col {
            get {
                return ResourceManager.GetString("NewDesc12Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc13.
        /// </summary>
        public static string NewDesc13Col {
            get {
                return ResourceManager.GetString("NewDesc13Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc14.
        /// </summary>
        public static string NewDesc14Col {
            get {
                return ResourceManager.GetString("NewDesc14Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc15.
        /// </summary>
        public static string NewDesc15Col {
            get {
                return ResourceManager.GetString("NewDesc15Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc1.
        /// </summary>
        public static string NewDesc1Col {
            get {
                return ResourceManager.GetString("NewDesc1Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc2.
        /// </summary>
        public static string NewDesc2Col {
            get {
                return ResourceManager.GetString("NewDesc2Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc3.
        /// </summary>
        public static string NewDesc3Col {
            get {
                return ResourceManager.GetString("NewDesc3Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc4.
        /// </summary>
        public static string NewDesc4Col {
            get {
                return ResourceManager.GetString("NewDesc4Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc5.
        /// </summary>
        public static string NewDesc5Col {
            get {
                return ResourceManager.GetString("NewDesc5Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc6.
        /// </summary>
        public static string NewDesc6Col {
            get {
                return ResourceManager.GetString("NewDesc6Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc7.
        /// </summary>
        public static string NewDesc7Col {
            get {
                return ResourceManager.GetString("NewDesc7Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc8.
        /// </summary>
        public static string NewDesc8Col {
            get {
                return ResourceManager.GetString("NewDesc8Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDesc9.
        /// </summary>
        public static string NewDesc9Col {
            get {
                return ResourceManager.GetString("NewDesc9Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDescription.
        /// </summary>
        public static string NewDescriptionCol {
            get {
                return ResourceManager.GetString("NewDescriptionCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewType.
        /// </summary>
        public static string NewTypeCol {
            get {
                return ResourceManager.GetString("NewTypeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldCode.
        /// </summary>
        public static string OldCodeCol {
            get {
                return ResourceManager.GetString("OldCodeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc1.
        /// </summary>
        public static string OldDesc1Col {
            get {
                return ResourceManager.GetString("OldDesc1Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc2.
        /// </summary>
        public static string OldDesc2Col {
            get {
                return ResourceManager.GetString("OldDesc2Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc3.
        /// </summary>
        public static string OldDesc3Col {
            get {
                return ResourceManager.GetString("OldDesc3Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc4.
        /// </summary>
        public static string OldDesc4Col {
            get {
                return ResourceManager.GetString("OldDesc4Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc5.
        /// </summary>
        public static string OldDesc5Col {
            get {
                return ResourceManager.GetString("OldDesc5Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc6.
        /// </summary>
        public static string OldDesc6Col {
            get {
                return ResourceManager.GetString("OldDesc6Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDesc7.
        /// </summary>
        public static string OldDesc7Col {
            get {
                return ResourceManager.GetString("OldDesc7Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldDescription.
        /// </summary>
        public static string OldDescriptionCol {
            get {
                return ResourceManager.GetString("OldDescriptionCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldType.
        /// </summary>
        public static string OldTypeCol {
            get {
                return ResourceManager.GetString("OldTypeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLinkId.
        /// </summary>
        public static string ProductLinkIdCol {
            get {
                return ResourceManager.GetString("ProductLinkIdCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue1.
        /// </summary>
        public static string SearchProdAttributeParm1 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue10.
        /// </summary>
        public static string SearchProdAttributeParm10 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue11.
        /// </summary>
        public static string SearchProdAttributeParm11 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue12.
        /// </summary>
        public static string SearchProdAttributeParm12 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue13.
        /// </summary>
        public static string SearchProdAttributeParm13 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue14.
        /// </summary>
        public static string SearchProdAttributeParm14 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue15.
        /// </summary>
        public static string SearchProdAttributeParm15 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue2.
        /// </summary>
        public static string SearchProdAttributeParm2 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue3.
        /// </summary>
        public static string SearchProdAttributeParm3 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue4.
        /// </summary>
        public static string SearchProdAttributeParm4 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue5.
        /// </summary>
        public static string SearchProdAttributeParm5 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue6.
        /// </summary>
        public static string SearchProdAttributeParm6 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue7.
        /// </summary>
        public static string SearchProdAttributeParm7 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue8.
        /// </summary>
        public static string SearchProdAttributeParm8 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AttributeValue9.
        /// </summary>
        public static string SearchProdAttributeParm9 {
            get {
                return ResourceManager.GetString("SearchProdAttributeParm9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichProductCode.
        /// </summary>
        public static string SearchProdCodeParm {
            get {
                return ResourceManager.GetString("SearchProdCodeParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichProductDescription.
        /// </summary>
        public static string SearchProdDescription {
            get {
                return ResourceManager.GetString("SearchProdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @whichProductType.
        /// </summary>
        public static string SearchProdTypeParm {
            get {
                return ResourceManager.GetString("SearchProdTypeParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBus].[dbo].[up_xferProductAttributeSearch].
        /// </summary>
        public static string SearchProductsByAttributes {
            get {
                return ResourceManager.GetString("SearchProductsByAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NWHBus].[dbo].[up_xferProductSearch].
        /// </summary>
        public static string SearchProductsByDescriptionOrCode {
            get {
                return ResourceManager.GetString("SearchProductsByDescriptionOrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string SortCodeCol {
            get {
                return ResourceManager.GetString("SortCodeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SortDescCol {
            get {
                return ResourceManager.GetString("SortDescCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _tblSearchReturnData.
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
